coverage:
  round: nearest
  ignore:
    - streams_map_incoming_bidi.go
    - streams_map_incoming_uni.go
    - streams_map_outgoing_bidi.go
    - streams_map_outgoing_uni.go
    - http3/gzip_reader.go
    - interop/
    - core/ackhandler/packet_linkedlist.go
    - core/utils/byteinterval_linkedlist.go
    - core/utils/newconnectionid_linkedlist.go
    - core/utils/packetinterval_linkedlist.go
    - core/utils/linkedlist/linkedlist.go
    - quictrace/
    - fuzzing/
  status:
    project:
      default:
        threshold: 0.5
    patch: false
